// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent for generating alternative introductory statements.
 *
 * - generateIntro - A function that generates introductory statements.
 * - GenerateIntroInput - The input type for the generateIntro function.
 * - GenerateIntroOutput - The return type for the generateIntro function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateIntroInputSchema = z.object({
  qualifications: z
    .string()
    .describe('The user\'s professional qualifications and experience.'),
});
export type GenerateIntroInput = z.infer<typeof GenerateIntroInputSchema>;

const GenerateIntroOutputSchema = z.object({
  introStatement: z
    .string()
    .describe('An alternative introductory statement for the user\'s portfolio.'),
});
export type GenerateIntroOutput = z.infer<typeof GenerateIntroOutputSchema>;

export async function generateIntro(input: GenerateIntroInput): Promise<GenerateIntroOutput> {
  return generateIntroFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateIntroPrompt',
  input: {schema: GenerateIntroInputSchema},
  output: {schema: GenerateIntroOutputSchema},
  prompt: `You are a personal branding expert. Generate an alternative introductory statement for a portfolio based on the following qualifications and experience:

{{{qualifications}}}

The introductory statement should be concise and compelling, highlighting the user's key strengths and career goals.`,
});

const generateIntroFlow = ai.defineFlow(
  {
    name: 'generateIntroFlow',
    inputSchema: GenerateIntroInputSchema,
    outputSchema: GenerateIntroOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
